version: '3.8'

services:
  streambox:
    build: .
    container_name: streambox
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./data.db:/app/data.db
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BIN_CHANNEL_ID=${BIN_CHANNEL_ID}
      - NODE_ENV=production
