services:
  - type: web
    name: telegram-file-stream
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BIN_CHANNEL_ID
        sync: false
